"use client";
import { Poppins } from "next/font/google";
import useBreakpoint from "use-breakpoint";
import Navigation from "@/components/navigation/Navigation";
import NavigationMobile from "@/components/navigation/NavigationMobile";
import "./globals.css";

export const metadata = {
  title: "Nelvex",
  description: "Generated by Next.js",
};
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

type DashboardLayoutProps = {
  children: React.ReactNode;
};

const BREAKPOINTS = { mobile: 0, desktop: 678 };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { breakpoint } = useBreakpoint(BREAKPOINTS, "mobile");

  return (
    <html lang="en">
      <body>
        {breakpoint === "mobile" ? (
          <NavigationMobile></NavigationMobile>
        ) : (
          <Navigation />
        )}
        {children}
      </body>
    </html>
  );
}
