import { Poppins } from "next/font/google";
import Navigation from "@/components/navigation/Navigation"
import ContextProvider  from './Context/store';
import "./globals.css";
import Session from "./Context/session";

export const metadata = {
  title: "Nelvex",
  description: "Generated by Next.js",
};
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <Session>
      <ContextProvider>
        <body className={poppins.className}>
        <Navigation></Navigation>
          {children}
        </body>
        </ContextProvider>
        </Session>
    </html>
  );
}
